const TRIP_DATA = {
  days: [
    {
      id: 0,
      label: "Day 0",
      title: "抵达 · 在 Taksim 落脚",
      area: "IST 机场 → Lokalist Istanbul",
      date: "OCT 30 · FRI",
      summary: "晚间抵达，只处理入境、接送与入住，把体力留给两个完整游览日。",
      image: "assets/images/bosphorus.jpg",
      color: "terracotta",
      items: [
        { time: "晚间", title: "抵达伊斯坦布尔 IST", meta: "入境、取行李与通信准备 · 预留约 60–90 分钟", type: "transfer" },
        { time: "落地 +90", title: "酒店预约接送", meta: "IST → Lokalist Istanbul，通常约 60–90 分钟", type: "transfer" },
        { time: "入住后", title: "办理入住 · Lokalist Istanbul", meta: "Taksim 附近连住三晚，不在短途旅行中搬酒店", type: "stay" },
        { time: "睡前", title: "确认次日票券与天气", meta: "托普卡帕、地下水宫、Hodjapasha 电子票离线保存", type: "note" }
      ]
    },
    {
      id: 1,
      label: "Day 1",
      title: "历史半岛 · 帝国的层叠",
      area: "Taksim → Sultanahmet → Sirkeci",
      date: "OCT 31 · SAT",
      summary: "从托普卡帕一路向西，再转向 Sirkeci；提前吃晚餐，19:00 安静观看旋转舞。",
      image: "assets/images/hagia-sophia.jpg",
      color: "blue",
      items: [
        { time: "09:00", title: "酒店出发前往老城", meta: "步行至 Taksim → F1 至 Kabataş → T1 至 Gülhane", type: "transfer" },
        { time: "09:45", title: "托普卡帕宫", attraction: "topkapi", meta: "09:45–12:00 · 后宫、珍宝馆、圣物馆、第四庭院" },
        { time: "12:10", title: "圣索菲亚大教堂", attraction: "hagia-sophia", meta: "12:10–13:00 · 游客参观层，重点看穹顶与回廊" },
        { time: "13:05", title: "Deraliye 一带午餐", meta: "13:05–13:45 · 控制为 40 分钟奥斯曼菜简餐", type: "food" },
        { time: "13:50", title: "蓝色清真寺", attraction: "blue-mosque", meta: "13:50–14:25 · 如遇礼拜暂停，与地下水宫对调" },
        { time: "14:35", title: "地下水宫", attraction: "basilica-cistern", meta: "14:35–15:20 · 柱林倒影、美杜莎头像与艺术装置" },
        { time: "15:20", title: "T1 前往 Beyazıt", meta: "Sultanahmet → Beyazıt · 比步行节省约 15–20 分钟", type: "transfer" },
        { time: "15:35", title: "大奖集市", attraction: "grand-bazaar", meta: "15:35–16:40 · 主街、Zincirli Han、地毯与陶瓷区" },
        { time: "16:40", title: "T1 前往 Sirkeci", meta: "Beyazıt → Sirkeci，再步行至餐厅", type: "transfer" },
        { time: "17:05", title: "Olden 1772 提前晚餐", meta: "17:05–18:20 · 订位注明 18:20 前结账", type: "food" },
        { time: "18:30", title: "Hodjapasha 展览与入场", attraction: "hodjapasha", meta: "提前 30 分钟签到，先看服饰、乐器与鲁米诗歌展" },
        { time: "19:00", title: "苏菲旋转舞仪式", attraction: "hodjapasha", meta: "19:00–20:00 · 保持安静，仪式中禁止拍照录像" },
        { time: "20:05", title: "返回 Lokalist Istanbul", meta: "T1 至 Kabataş → F1 至 Taksim → 步行，约 20:50 到店", type: "transfer" }
      ]
    },
    {
      id: 2,
      label: "Day 2",
      title: "现代伊斯坦布尔 · 海峡与艺术",
      area: "Dolmabahçe → Tophane → Eminönü → Pera",
      date: "NOV 01 · SUN",
      summary: "宫殿只看 90 分钟精华；从当代艺术走向海峡，再经 Karaköy 与独立大街步行回酒店。",
      image: "assets/images/karakoy.jpg",
      color: "gold",
      items: [
        { time: "09:00", title: "酒店出发前往宫殿", meta: "出租车直达多尔玛巴赫切宫 · 约 15 分钟", type: "transfer" },
        { time: "09:15", title: "多尔玛巴赫切宫", attraction: "dolmabahce", meta: "09:15–10:45 · 主宫、水晶楼梯、仪式大厅与海峡宫门" },
        { time: "10:45", title: "前往 Tophane", meta: "步行至 Kabataş，乘 T1 至 Tophane", type: "transfer" },
        { time: "11:10", title: "伊斯坦布尔现代艺术博物馆", attraction: "istanbul-modern", meta: "11:10–12:40 · 常设展、摄影展与顶层观景平台" },
        { time: "12:40", title: "Galataport 午餐", attraction: "karakoy-galataport", meta: "12:40–13:35 · 选择出餐快的海滨餐厅" },
        { time: "13:35", title: "T1 前往 Eminönü 码头", meta: "Tophane → Eminönü；14:05 前找到 Şehir Hatları 官方售票处", type: "transfer" },
        { time: "14:05", title: "购票与候船", meta: "只认 Şehir Hatları 官方售票窗口，避开私人游船揽客", type: "note" },
        { time: "14:40", title: "博斯普鲁斯短线公共游船", attraction: "bosphorus-cruise", meta: "14:40–约 16:40 · 上层露天甲板靠船尾" },
        { time: "16:40", title: "加拉塔桥步行", attraction: "karakoy-galataport", meta: "16:40–17:05 · 把跨桥观景融入前往 Karaköy 的交通" },
        { time: "17:05", title: "Karaköy 咖啡休息", attraction: "karakoy-galataport", meta: "17:05–17:35 · 不登加拉塔塔，不额外绕路" },
        { time: "17:35", title: "F2 地下缆车至 Tünel", meta: "避开陡坡，直接抵达独立大街南端", type: "transfer" },
        { time: "17:50", title: "独立大街文化步行", attraction: "istiklal", meta: "17:50–19:10 · 从 Tünel 持续向 Taksim 推进" },
        { time: "19:15", title: "Pera／独立大街晚餐", meta: "19:15–20:45 · 提前预约，可选屋顶景观餐厅", type: "food" },
        { time: "20:45", title: "独立大街夜景与 AKM 外观", attraction: "istiklal", meta: "步行返回 Taksim 附近酒店，约 21:15 收尾" }
      ]
    },
    {
      id: 3,
      label: "Day 3",
      title: "返程 · 13:30 飞往上海",
      area: "Lokalist Istanbul → IST",
      date: "NOV 02 · MON",
      summary: "不再新增景点，09:00 准时离店，为国际航班、安检和步行距离留足缓冲。",
      image: "assets/images/istiklal.jpg",
      color: "sage",
      items: [
        { time: "07:30", title: "起床与整理行李", meta: "确认航站楼、退税材料与机场接送车辆", type: "stay" },
        { time: "08:00", title: "酒店早餐", meta: "08:00–08:40 · 不再安排酒店范围外的散步", type: "food" },
        { time: "08:40", title: "办理退房", meta: "08:55 前完成人员与行李确认", type: "stay" },
        { time: "09:00", title: "专车前往 IST 机场", meta: "周一早高峰；若下雨或需要退税，可提前至 08:30", type: "transfer" },
        { time: "10:15", title: "抵达机场", meta: "预留入口安检、值机、出境及前往远端登机口时间", type: "note" },
        { time: "13:30", title: "起飞返回上海", meta: "国际航班至少提前 3 小时抵达机场", type: "transfer" }
      ]
    }
  ],
  attractions: {
    "blue-mosque": {
      name: "蓝色清真寺",
      localName: "Sultanahmet Camii",
      kicker: "THE RHYTHM OF PRAYER",
      district: "Sultanahmet · Fatih",
      image: "assets/images/blue-mosque.jpg",
      photoCredit: "Alex Azabache / Pexels",
      intro: "六座宣礼塔与层层下降的穹顶，让它成为奥斯曼古典建筑最有辨识度的轮廓。真正走进内部，蓝色伊兹尼克瓷砖、彩绘穹顶与透过两百多扇窗的光，才是名字背后的答案。",
      quote: "不要只寻找蓝色；先抬头，看光如何让穹顶悬浮。",
      fee: "免费入场，捐赠自愿",
      hours: "每日开放；通常 08:30–11:30、13:00–14:30、15:30–16:45。周五游客参观约 13:30 后开始。",
      duration: "30–45 分钟",
      bestTime: "08:30 第一时段",
      transit: "T1 电车至 Sultanahmet，步行约 3 分钟。",
      highlights: ["六座宣礼塔", "伊兹尼克瓷砖", "中央穹顶与彩窗", "面对圣索菲亚的庭院轴线"],
      photoSpots: [
        { title: "Sultanahmet 广场长椅", text: "站在两座建筑之间，以喷泉和花园做前景；清晨游客更少。" },
        { title: "清真寺西侧庭院", text: "用拱廊框住穹顶与宣礼塔，是最有层次的对称构图。" },
        { title: "竞技场南端", text: "稍微拉远，可拍下六座宣礼塔完整展开的城市天际线。" }
      ],
      tips: ["进入祈祷大厅前需脱鞋，入口会提供鞋袋。", "肩膀和膝盖需遮盖；女性需戴头巾，入口通常可借用。", "禁止闪光灯，不要拍摄正在祈祷的人。", "祷告时段每日变化，前一晚再次查看官网。"],
      official: "https://bluemosque.tr/visit/",
      map: "https://www.google.com/maps/search/?api=1&query=Blue+Mosque+Istanbul"
    },
    "hagia-sophia": {
      name: "圣索菲亚大教堂",
      localName: "Ayasofya-i Kebîr Câmi-i Şerîfi",
      kicker: "A DOME ACROSS EMPIRES",
      district: "Sultanahmet · Fatih",
      image: "assets/images/hagia-sophia.jpg",
      photoCredit: "Mihman / Pexels",
      intro: "公元 537 年落成后，这座巨构先后成为东罗马教堂、奥斯曼清真寺、博物馆，再回到清真寺。如今游客主要沿上层回廊参观，在拜占庭马赛克、巨型伊斯兰书法圆盘和穹顶之间，看见城市历史并置而非替换。",
      quote: "这里最动人的不是某一种文明，而是它们仍在同一空间里彼此凝视。",
      fee: "外国游客上层回廊约 €25；礼拜区域规则另计",
      hours: "每日开放，游客时段会随季节与祷告调整；夏季通常延长至 19:00 左右。",
      duration: "60–75 分钟",
      bestTime: "开门后或傍晚",
      transit: "T1 电车至 Sultanahmet，穿过广场步行约 5 分钟。",
      highlights: ["直径约 31 米的中央穹顶", "上层回廊马赛克", "巨型书法圆盘", "拜占庭与奥斯曼构件并置"],
      photoSpots: [
        { title: "Sultanahmet 公园喷泉", text: "对称正面最经典，清晨顺光，蓝色时刻则适合拍灯光。" },
        { title: "上层回廊南侧", text: "从栏杆望向中殿，可同时纳入穹顶、吊灯与书法圆盘。" },
        { title: "西南侧小巷", text: "利用木屋和石墙做前景，画面比广场正面更有生活感。" }
      ],
      tips: ["仍是宗教场所，请穿着得体并保持安静。", "大型修复工程可能出现脚手架，部分视角会临时受限。", "安检和购票队伍分开，旺季预留至少 30 分钟排队。", "不要从非官方兜售者处购买所谓免排队票。"],
      official: "https://www.ayasofyacamii.gov.tr/",
      map: "https://www.google.com/maps/search/?api=1&query=Hagia+Sophia+Istanbul"
    },
    "basilica-cistern": {
      name: "地下水宫",
      localName: "Yerebatan Sarnıcı",
      kicker: "BENEATH THE CITY",
      district: "Sultanahmet · Fatih",
      image: "assets/images/cistern.jpg",
      photoCredit: "Hatice Baran / Pexels",
      intro: "六世纪的地下蓄水工程，由 336 根形态各异的石柱托起。修复后的步道、浅水反射和当代艺术装置，让它不只是遗迹，更像一段被精心编排的地下叙事。",
      quote: "城市在头顶喧闹，而这里的时间只沿着水面移动。",
      fee: "09:00–18:30 外国游客 1,950 TL；19:30–22:00 夜场 3,000 TL",
      hours: "每日 09:00–22:00；18:30–19:30 为场次切换。",
      duration: "45–60 分钟",
      bestTime: "09:00 开门即入场",
      transit: "T1 电车至 Sultanahmet，沿 Yerebatan Caddesi 步行约 2 分钟。",
      highlights: ["336 根石柱", "两座美杜莎头像柱础", "泪柱", "水面反射与艺术装置"],
      photoSpots: [
        { title: "入口后的首段长廊", text: "用连续柱列制造消失点，手机夜景模式即可，避免过度曝光灯光。" },
        { title: "美杜莎头像区域", text: "稍候人流间隙，低机位纳入水面倒影，画面更完整。" },
        { title: "泪柱前", text: "侧面光最能强调柱身纹理，适合拍局部而非全景。" }
      ],
      tips: ["仅接受银行卡或 İstanbulkart，现场不收现金。", "Museum Pass 不适用；这里由伊斯坦布尔市属机构运营。", "地面潮湿且光线低，穿防滑鞋并放慢脚步。", "三脚架通常不便使用，拍照时不要阻挡狭窄步道。"],
      official: "https://yerebatan.com/en/basilica-cistern/visit-info/",
      map: "https://www.google.com/maps/search/?api=1&query=Basilica+Cistern+Istanbul"
    },
    "topkapi": {
      name: "托普卡帕宫",
      localName: "Topkapı Sarayı",
      kicker: "THE IMPERIAL COURT",
      district: "Sarayburnu · Fatih",
      image: "assets/images/topkapi.jpg",
      photoCredit: "Zak H / Pexels",
      intro: "它不是一栋孤立的大宫殿，而是由四重庭院、议政空间、宝库、圣物室与后宫组成的皇城。路线从礼制严谨的前朝逐步走向私密生活，最后抵达俯瞰博斯普鲁斯的露台。",
      quote: "越往宫殿深处走，帝国越从仪式变成日常。",
      fee: "外国游客联票 2,750 TL，含主宫、后宫与圣伊莲娜教堂",
      hours: "09:00–17:00 售票；周二闭馆。",
      duration: "本行程 2 小时 15 分",
      bestTime: "09:45 入场后优先后宫",
      transit: "T1 电车至 Gülhane 或 Sultanahmet，步行约 8–10 分钟。",
      highlights: ["帝国议事厅", "后宫瓷砖房间", "皇家宝库", "第四庭院海峡露台"],
      photoSpots: [
        { title: "幸福之门", text: "站在第二庭院中轴拍摄，屋檐、门洞和两侧树木形成天然对称。" },
        { title: "后宫瓷砖长廊", text: "用门框叠出纵深，注意室内通常禁止闪光。" },
        { title: "第四庭院 İftariye 凉亭", text: "金角湾与博斯普鲁斯同时入镜，是宫内最开阔的观景点。" }
      ],
      tips: ["本次安排在周六，闭馆日没有冲突。", "高效路线：第二庭院 → 后宫 → 珍宝馆 → 圣物馆 → 第四庭院。", "联票自购买日起仅 1 天有效，不适合拆成两天游览。", "12:00 必须离开前往圣索菲亚，普通瓷器展厅可略过。"],
      official: "https://www.millisaraylar.gov.tr/Lokasyon/2/topkapi-sarayi",
      map: "https://www.google.com/maps/search/?api=1&query=Topkapi+Palace+Istanbul"
    },
    "dolmabahce": {
      name: "多尔玛巴赫切宫",
      localName: "Dolmabahçe Sarayı",
      kicker: "THE LAST OTTOMAN PALACE",
      district: "Beşiktaş",
      image: "assets/images/dolmabahce.jpg",
      photoCredit: "M. Emin Bilir / Pexels",
      intro: "十九世纪的奥斯曼帝国在海峡边建起一座面向欧洲的宫殿。巴洛克、洛可可和新古典装饰与传统宫廷格局并存，水晶阶梯和典礼大厅把晚期帝国的雄心推到极致。",
      quote: "一边是欧洲宫廷的华丽，一边是博斯普鲁斯最克制的蓝。",
      fee: "外国游客联票 2,000 TL，含 Selamlık、后宫与绘画博物馆",
      hours: "09:00–17:00 售票；周一闭馆。",
      duration: "本行程 90 分钟精华",
      bestTime: "09:15–10:45",
      transit: "T1 电车至 Kabataş 后沿海步行约 8 分钟。",
      highlights: ["水晶阶梯", "典礼大厅巨型吊灯", "海峡门", "阿塔图尔克纪念房间"],
      photoSpots: [
        { title: "宫殿海峡门", text: "庭院内向海拍，雕花石门会将水面和亚洲岸框成一幅画。" },
        { title: "钟楼广场", text: "从斜侧面拍钟楼与宫门，上午光线更干净。" },
        { title: "博斯普鲁斯轮渡上", text: "从水上才能看见宫殿沿海展开的完整立面。" }
      ],
      tips: ["本次安排在周日，周一闭馆不会影响行程。", "只走主宫、水晶楼梯、仪式大厅、阿塔图尔克房间与海峡宫门。", "跳过后宫大部分普通房间及绘画博物馆，10:45 准时离开。", "内部通常禁止摄影，按现场规定收起手机和相机。"],
      official: "https://www.millisaraylar.gov.tr/Lokasyon/3/Dolmabahce-Palace",
      map: "https://www.google.com/maps/search/?api=1&query=Dolmabahce+Palace+Istanbul"
    },
    "istiklal": {
      name: "独立大街",
      localName: "İstiklal Caddesi",
      kicker: "THE CITY'S LIVING ROOM",
      district: "Beyoğlu",
      image: "assets/images/istiklal.jpg",
      photoCredit: "_feyzzza_ / Pexels",
      intro: "从塔克西姆广场向南延伸约 1.4 公里，红色怀旧电车穿过书店、教堂、拱廊、电影院与甜品店。它不只是购物街，而是理解伊斯坦布尔现代城市生活最直接的一条剖面。",
      quote: "别急着走完一条街；真正的惊喜通常藏在拱廊和支路里。",
      fee: "街区免费；怀旧电车按公共交通票价",
      hours: "全天开放；商店多为 10:00–22:00。",
      duration: "本行程 1 小时 20 分",
      bestTime: "17:50 从 Tünel 出发",
      transit: "Karaköy 乘 F2 地下缆车至 Tünel，再从南向北步行回 Taksim。",
      highlights: ["怀旧红色电车", "圣安多尼教堂", "Çiçek Pasajı", "Salt Beyoğlu 与独立书店"],
      photoSpots: [
        { title: "电车转弯处", text: "在安全距离外用长焦压缩街景，红色电车和建筑立面会更集中。" },
        { title: "圣安多尼教堂前院", text: "从大街门洞向内拍，喧闹街道与安静红砖形成反差。" },
        { title: "Tünel 广场", text: "傍晚灯光亮起时，老电车、坡道和街角咖啡馆最有城市感。" }
      ],
      tips: ["周日晚人流密集，手机和钱包放在身体前侧。", "本次由 Tünel 向 Taksim 行进，终点就是酒店附近，不走回头路。", "19:15 前抵达 Pera／独立大街的预约餐厅。", "避开主动拉客且没有明码标价的酒吧。"],
      official: "https://visit.istanbul/istiklal-street",
      map: "https://www.google.com/maps/search/?api=1&query=Istiklal+Avenue+Istanbul"
    },
    "galata-tower": {
      name: "加拉塔塔",
      localName: "Galata Kulesi",
      kicker: "ABOVE THE GOLDEN HORN",
      district: "Galata · Beyoğlu",
      image: "assets/images/galata-skyline.jpg",
      photoCredit: "Zmutaqin / Pexels",
      intro: "十四世纪的热那亚人把它建成城墙瞭望塔。如今电梯把游客送到高处，再沿展层向下，在 360 度观景台辨认金角湾、历史半岛、博斯普鲁斯与亚洲岸。",
      quote: "日落时整座城会变成一张地图，而海峡是最亮的那条线。",
      fee: "外国游客约 €30；Museum Pass İstanbul 可用于日间",
      hours: "日间 08:30–18:30；夜间博物馆 18:30–23:00，末次售票 22:00。",
      duration: "60–90 分钟",
      bestTime: "日落前 60 分钟",
      transit: "M2 至 Şişhane 后步行下坡 8 分钟；或从 Karaköy 步行上坡。",
      highlights: ["360° 环形观景台", "金角湾与历史半岛全景", "热那亚城墙历史", "逐层下行的城市展览"],
      photoSpots: [
        { title: "观景台南侧", text: "面向历史半岛，圣索菲亚与苏莱曼尼耶清真寺会在海面上展开。" },
        { title: "Büyük Hendek Caddesi", text: "沿北侧街道稍微拉远，用两侧建筑夹出塔身，清晨最好拍。" },
        { title: "Serdar-ı Ekrem 坡道", text: "石板路、旧公寓与塔顶共同入镜，适合街头感构图。" }
      ],
      tips: ["观景台狭窄且风大，帽子和轻物要收好。", "日落前常排长队，至少提前 45–60 分钟到达。", "Museum Pass 只适用于规定日间时段，夜场不适用。", "18 岁以下需由监护人陪同。"],
      official: "https://www.muze.gov.tr/muze-detay?DistId=MRK&SectionId=GLT04",
      map: "https://www.google.com/maps/search/?api=1&query=Galata+Tower+Istanbul"
    },
    "bosphorus-cruise": {
      name: "博斯普鲁斯海峡游船",
      localName: "Boğaz Turu",
      kicker: "BETWEEN TWO CONTINENTS",
      district: "Eminönü / Karaköy",
      image: "assets/images/bosphorus.jpg",
      photoCredit: "Umut Izgi / Pexels",
      intro: "伊斯坦布尔最好的城市视角在水上。短线游船会从历史半岛与加拉塔之间出发，经过多尔玛巴赫切宫、奥塔科伊、两座跨海大桥与亚洲岸木屋，在海鸥和渡轮声里理解这座城市的尺度。",
      quote: "这不是离开城市，而是终于看见城市的全貌。",
      fee: "Şehir Hatları 短线：外国游客 340 TL",
      hours: "当前 Eminönü 官方短线每日 14:40 发船；冬季时刻需临近复核。",
      duration: "约 2 小时",
      bestTime: "14:05 到码头，14:40 开船",
      transit: "T1 至 Eminönü，或轮渡 / 电车至 Karaköy 后前往码头。",
      highlights: ["多尔玛巴赫切宫水岸立面", "奥塔科伊清真寺与大桥", "鲁梅利堡", "欧亚两岸木屋与天际线"],
      photoSpots: [
        { title: "船尾外侧甲板", text: "更少玻璃反光，也能拍下逐渐远去的历史半岛天际线。" },
        { title: "奥塔科伊段", text: "提前站在欧洲岸一侧，让清真寺与第一大桥在同一画面叠合。" },
        { title: "返航蓝色时刻", text: "提高快门保持船上清晰，利用城市灯光在水面的反射。" }
      ],
      tips: ["只在 Şehir Hatları 官方售票处购票，不接受私人游船揽客。", "11 月海上体感温度可能比陆地低约 5℃，准备防风外套。", "去程优先欧洲岸一侧，返程换另一侧或船尾。", "正式冬季时刻表可能调整，10 月中旬必须再确认一次。"],
      official: "https://sehirhatlari.istanbul/en/timetables/bosphorus-tours/short-bosphorus-tour-181",
      map: "https://www.google.com/maps/search/?api=1&query=Eminonu+Bosphorus+Cruise+Pier"
    },
    "grand-bazaar": {
      name: "大奖集市",
      localName: "Kapalıçarşı",
      kicker: "A CITY UNDER ONE ROOF",
      district: "Beyazıt · Fatih",
      image: "assets/images/grand-bazaar.jpg",
      photoCredit: "Beyzanur / Pexels",
      intro: "从十五世纪的核心商栈发展为覆盖数十条街巷的室内市场，拱顶下交织着珠宝、地毯、陶瓷、灯具与皮具店。这里最值得看的不仅是商品，还有仍在运转的商贸传统、院落和层层相接的街道结构。",
      quote: "把它当成一座有屋顶的城市，而不是一间巨大的纪念品商店。",
      fee: "免费进入，购物另计",
      hours: "通常周一至周六 09:00–19:00；周日关闭。",
      duration: "本行程 65 分钟",
      bestTime: "15:35–16:40",
      transit: "T1 电车至 Beyazıt；从 Beyazıt 或 Nuruosmaniye 一侧进入。",
      highlights: ["Kalpakçılar 珠宝主街", "Old Bedesten", "Zincirli Han 红色庭院", "地毯与伊兹尼克陶瓷区"],
      photoSpots: [
        { title: "Zincirli Han 庭院", text: "红色立面、绿植与石阶形成鲜明色块，午后光线柔和。" },
        { title: "珠宝主街拱顶中央", text: "站在不妨碍人流的位置，利用连续拱顶制造对称消失点。" },
        { title: "Old Bedesten 门洞", text: "用厚重石门框住内部摊位，能表现市场最古老的建筑层次。" }
      ],
      tips: ["本次必须周六游览，周日大量商户关闭。", "预设路线行进，不深入外围小巷，16:40 准时离开。", "高价商品要求发票与材质证明，不仓促购买地毯或珠宝。", "T1 和市场内人流密集，手机与钱包放在身体前侧。"],
      official: "https://visit.istanbul/grand-bazaar",
      map: "https://www.google.com/maps/search/?api=1&query=Grand+Bazaar+Istanbul"
    },
    "hodjapasha": {
      name: "苏菲旋转舞",
      localName: "Hodjapasha Sema Ceremony",
      kicker: "A RITUAL OF STILLNESS",
      district: "Sirkeci · Fatih",
      image: "assets/images/dervish.jpg",
      photoCredit: "Emin Bozyokuş / Pexels",
      intro: "Hodjapasha 位于一座十五世纪浴室改建的文化中心。这里的 Sema 更接近一场带有宗教象征的静默仪式：音乐、吟诵与旋转共同表现从自我走向精神完善的旅程。",
      quote: "真正的观看方式不是追随旋转，而是在旋转中感受安静。",
      fee: "官网当前 19:00 场约 US$42.22 起",
      hours: "每日 19:00；仪式约 60 分钟，建议提前 30 分钟签到。",
      duration: "展览 30 分钟 + 仪式 60 分钟",
      bestTime: "18:30 入场，19:00 开始",
      transit: "T1 至 Sirkeci，步行约 5 分钟；从 Olden 1772 一带步行约 5–8 分钟。",
      highlights: ["Mevlevi Sema 仪式", "现场传统音乐", "鲁米诗歌与苏菲文化展", "十五世纪浴室穹顶空间"],
      photoSpots: [
        { title: "入口历史石墙", text: "仪式开始前拍摄建筑外观，避开狭窄街巷的人流。" },
        { title: "前厅展览区", text: "服饰、乐器和雕塑是否可拍以现场标识为准。" },
        { title: "把相机收起来", text: "仪式期间禁止拍照录像；这一小时更适合专心观看。" }
      ],
      tips: ["18:30 前签到，迟到可能无法入场。", "仪式中禁止摄影、录像和交谈，手机全程静音。", "7 岁以下儿童不适合参加；场地对轮椅并不友好。", "座位通常按订票先后安排，建议提前购买。"],
      official: "https://hodjapasha.com/en/",
      map: "https://www.google.com/maps/search/?api=1&query=Hodjapasha+Culture+Center+Istanbul"
    },
    "istanbul-modern": {
      name: "伊斯坦布尔现代艺术博物馆",
      localName: "İstanbul Modern",
      kicker: "ART ON THE WATERFRONT",
      district: "Tophane · Beyoğlu",
      image: "assets/images/karakoy.jpg",
      photoCredit: "Yaşar Başkurt / Pexels",
      intro: "土耳其首座现代与当代艺术博物馆坐落在 Karaköy 海岸，由伦佐·皮亚诺设计。馆藏从 1945 年延伸至当代，建筑顶层的反射水池与观景平台又把博斯普鲁斯和历史半岛纳入参观体验。",
      quote: "从展厅走到屋顶，城市本身成为最后一件作品。",
      fee: "外国成人 900 TL；一张票可参观全部展览",
      hours: "周日 10:00–18:00；周一闭馆，周五延长至 20:00。",
      duration: "本行程 90 分钟",
      bestTime: "11:10–12:40",
      transit: "T1 至 Tophane，步行约 3–5 分钟；入口位于 Galataport 内。",
      highlights: ["土耳其现代艺术常设展", "摄影展厅", "伦佐·皮亚诺建筑", "屋顶反射水池与 360° 观景台"],
      photoSpots: [
        { title: "屋顶反射水池", text: "利用水面拍历史半岛天际线倒影；大风时注意镜头水雾。" },
        { title: "海滨步道", text: "从 Galataport 水边回望，最容易拍到博物馆鳞片般的立面。" },
        { title: "透明首层", text: "室内外视线贯通，可把人群、港口和建筑结构同时纳入。" }
      ],
      tips: ["路线固定为常设展 → 临时展 → 摄影展 → 顶层平台。", "12:40 准时离馆去午餐，避免影响 14:40 游船。", "当天票不可退换，官网当日线上售票通常在 17:00 关闭。", "大型行李需寄存，展厅摄影规则以现场标识为准。"],
      official: "https://www.istanbulmodern.org/en/visit/museum",
      map: "https://www.google.com/maps/search/?api=1&query=Istanbul+Modern"
    },
    "karakoy-galataport": {
      name: "Karaköy 与 Galataport",
      localName: "Karaköy · Galataport",
      kicker: "THE WATERFRONT REIMAGINED",
      district: "Karaköy · Beyoğlu",
      image: "assets/images/karakoy.jpg",
      photoCredit: "Yaşar Başkurt / Pexels",
      intro: "旧港口、金融街、咖啡馆和全新的海滨公共空间在这里叠合。白天的 Galataport 适合沿海午餐，游船返程后则从加拉塔桥步行进入 Karaköy，在街区喝杯咖啡，再用 F2 缆车避开陡坡。",
      quote: "一座港口如何更新，可以从海边走进一条旧街慢慢看。",
      fee: "公共街区与海滨步道免费；餐饮另计",
      hours: "公共空间通常全天可达；商铺及餐厅各自营业。",
      duration: "午餐 55 分钟 + 傍晚 55 分钟",
      bestTime: "12:40 午餐 / 16:40 后街区散步",
      transit: "T1 至 Tophane 或 Karaköy；前往独立大街可乘 F2 Karaköy–Tünel。",
      highlights: ["Galataport 海滨", "伊斯坦布尔现代", "加拉塔桥", "Karaköy 咖啡馆与旧建筑"],
      photoSpots: [
        { title: "加拉塔桥中段", text: "朝南拍新清真寺与老城天际线，朝北拍加拉塔山坡。" },
        { title: "Tophane 钟楼广场", text: "把历史钟楼、现代港口建筑与行人放入同一画面。" },
        { title: "Karaköy 后街", text: "银行街、涂鸦、咖啡馆和坡道最能表现街区日常。" }
      ],
      tips: ["游船后直接步行过加拉塔桥，不返回 Eminönü 乘车。", "17:35 前抵达 F2 入口，避免步行爬坡消耗体力。", "海滨餐厅需选择出餐快的店，13:35 必须离开。", "邮轮靠港时 Galataport 安检与人流可能增加。"],
      official: "https://galataport.com/en/",
      map: "https://www.google.com/maps/search/?api=1&query=Galataport+Istanbul"
    }
  }
};
